apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-apps
  template:
    metadata:
      labels:
        app: techno-apps
    spec:
      containers:
        - name: techno-flask-app
          image: 573411764112.dkr.ecr.us-east-1.amazonaws.com/techno-flask-project:latest
          ports:
            - containerPort: 2000