apiVersion: v1                 
kind: Service                  
metadata:
  name: techno-apps-service         
spec:
  type: LoadBalancer           
  selector:
    app: techno-apps              
  ports:
    - port: 80                 
      targetPort: 2000