apiVersion: v1
kind: Service
metadata:
  namespace: OPSML
  name: techno-opsml
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048